name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log Level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      
      - run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.logLevel }}"
          
      - name: checkout
        uses: actions/checkout@4.2.2
        
      - name: List files in the repository
        run: |
          echo "the repository ${{ github.repository }} contains the following files:"
          tree
      
      
